M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu22.04.1} date 2025-07-08T15:19:42+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-08T15:19:42+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.1462Y-3.4376
X3.3738Y-3.4376
T2
X2.14Y-3.49
X3.278Y-2.228
M30
